version: 2.1

commands:
  install_deps:
    description: "Install Dependencies"
    steps:
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache \
              py-pip \
              curl \
              curl-dev \
              bash \
              docker-compose 
      - run:
          name: Initialize Submodules
          command: |
            git submodule init &&
            git submodule update --remote
  build_images:
    description: "Builds Docker Images"
    steps:
      - run:
          name: Build Images
          command: |
            set +o pipefail
            sh buildscripts/buildSupportedAlpineImages.sh
  test_images:
    description: "Test Images"
    steps:
      - run:
          name: Test Images
          command: |
              sh buildscripts/testSupportedAlpineImages.sh
      - store_artifacts:
          path: report
  push_images:
    description: "Push Image to DockerHub"
    steps:
      - run:
          name: Push Images to DockerHub
          command: |
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              sh buildscripts/releaseSupportedAlpineImages.sh

jobs:
  build_branch:
    working_directory: /app
    docker:
      - image: docker:19.03.8-git
    steps:
      - checkout
      - setup_remote_docker
      - install_deps
      - build_images
      - test_images

  build_master:
    working_directory: /app
    docker:
      - image: docker:19.03.8-git
    steps:
      - checkout
      - setup_remote_docker
      - install_deps
      - build_images
      - test_images
      - push_images

  build_nightly:
    working_directory: /app
    environment:
      IMAGE_VERSION: nightly
    docker:
      - image: docker:19.03.8-git
    steps:
      - checkout
      - setup_remote_docker
      - install_deps
      - build_images
      - test_images
      - push_images

  build_tags:
    working_directory: /app
    docker:
      - image: docker:19.03.8-git
    steps:
      - checkout
      - setup_remote_docker
      - install_deps
      - build_images
      - test_images
      - push_images

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build_tags:
          filters:
            tags:
              only: /^\d+(\.\d+)+$/
            branches:
              ignore: /.*/
      - build_master:
          filters:
            branches:
              only: master
      - build_branch:
          filters:
            branches:
              ignore:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
